### ISSUE TITLE
Plugin fails to open .ico file

### ISSUE THREAD

**Issue by DataPlusProgram** [pkowal1982/godoticonplugin#1]
![image](https://user-images.githubusercontent.com/62811101/217250514-da923e79-b09e-4281-b8c4-1c1e66e208c2.png)

I have tried with the default godot.ico and it works correclty but these icons provided below don't work.

[icons.zip](https://github.com/pkowal1982/godoticonplugin/files/10675186/icons.zip)

**Comment by pkowal1982** [comment]
@DataPlusProgram You need to create your own ico file from one or more images. Best will be png format as it can hold transparency and is losless.

Take png, use it with **Icon Creator** and then apply icon to exported executable using **Icon Replacer**.

As you can see the icons provided are 4286 and 144468 bytes in size.
Icons which can be used with Icon Replacer are specially compressed and they have always size of 359559 bytes.
