### ISSUE TITLE
Will this plugin be updated for Godot v4.x?

### ISSUE THREAD

**Issue by ghost** [pkowal1982/godoticonplugin#2]
Was wondering if there are plans to update this plugin for Godot v4.x? I am moving to version 4 and the plugin is incompatible. Love this plugin as I am Mac and don't have to hassle with rcedit.

**Comment by ghost** [comment]
I think I answered my own question, it appears that version 1.0.1 works with Godot 4. I missed it on the plugin site. Sorry to bother you.

**Comment by pkowal1982** [comment]
@keithrdavis **PLEASE** add a comment about using it on Mac [here](https://github.com/godotengine/godot/issues/73497)
If there is enough comments in this thread we have chance native support for icon is added to 4.1.
 
You're right, there is a 4.0 plugin version but as you can see it can create icon for you but not replace it with standard 4.0 template.
Support for GodotIcon plugin (replace part) was broken with Godot 4.0 beta 7.
Still you can create your own template with these steps:

Login to your GitHub account.
Add your public SSH key to GitHub so you can push your changes later.
Fork [Godot sources](https://github.com/godotengine/godot) with button on top right part of screen.
Clone sources to your computer, remember to replace **YOUR_LOGIN** with real one:
```
git clone git@github.com:YOUR_LOGIN/godot.git
```
By default you should be on master branch.
```
cd godot
```
If you want to have official Godot 4.0 template:
```
git checkout 92bee43ad
git switch -c template
```
And if you want to use up to date sources:
```
git checkout -b template
```
Prepare icon with GodotIcon script or plugin and save it as:
```
godot/platform/windows/godot.ico
```
You can check that it's only file changed:
```
git status
```
Add your change:
```
git add *
```
Commit it to branch:
```
git commit -m "Fixed size icon template"
```
Push your changes to remote repository:
```
git push --set-upstream origin template
```
Visit your repository (replace login with real one):
```
https://github.com/YOUR_LOGIN/godot/actions
```
It will take about an hour to build your template.
When it's ready open **Windows builds** workflow.
On the bottom there's **Artifacts** section which should contain **windows-template** file.
Download it and set in your project as export template.
It will have icon you already set.
All binaries exported with this template will work with GodotIcon plugin.

**Comment by ghost** [comment]
Thank you so much for the information!

**Comment by pkowal1982** [comment]
Thanks for leaving comment. Closing this as I assume you'll be able to build your own template now.
