### ISSUE TITLE
Error: Wrong icon type, PNG signature missing with icon created by Icon Creator

### ISSUE THREAD

**Issue by SussyGuy35** [pkowal1982/godoticonplugin#3]

**Comment by pkowal1982** [comment]
@SussyGuy35 You need to provide details about what went wrong. Now it's hard to tell what happened. Event the plugin version is missing not mentioning about input and output.

**Comment by SussyGuy35** [comment]
@pkowal1982 I used Icon Creator to create an icon, then when I try to use Icon Replacer with that icon, it says this
![ảnh](https://user-images.githubusercontent.com/107260269/234428109-22265230-b8dc-47dd-893e-1171453a653a.png)
![ảnh](https://user-images.githubusercontent.com/107260269/234428164-5963ebbf-14f5-43d2-85d5-8c7a0b595f77.png)

**Comment by pkowal1982** [comment]
Please attach image you're using to create icon and resulting icon.
What version of Godot do you use? 3.5.2?

**Comment by SussyGuy35** [comment]
the image:
![njnk](https://user-images.githubusercontent.com/107260269/234499128-1538a674-deea-47d7-ae37-fbf55cd9a29d.png)
the resulting icon:
[icon.zip](https://github.com/pkowal1982/godoticonplugin/files/11330091/icon.zip)
im using godot 3.5.2. i tried multiple image, it alway says that error

**Comment by pkowal1982** [comment]
Just checked your icon on both Linux and Windows and it's working as expected. Could you please try command line version?

**Comment by SussyGuy35** [comment]
![ảnh](https://user-images.githubusercontent.com/107260269/234598076-e21a2327-3acb-4c32-a6e5-38266d566801.png)
I tried command line version, seems like it because my video card driver is very old and doesnt support gles3

**Comment by pkowal1982** [comment]
Try to run it this way (be sure paths are correct, everything is one line):
`Godot_v3.5.2-stable_win64.exe -s ReplaceIcon.gd dodge-da-creeps/njnk.ico dodge-da-creeps/build/game.exe --video-driver GLES2`

**Comment by SussyGuy35** [comment]
@pkowal1982 
![ảnh](https://user-images.githubusercontent.com/107260269/234757990-1ac27ef9-4742-473b-a431-440f3d4fdd85.png)

**Comment by pkowal1982** [comment]
Please try this version of script with extended debugging info:
[ReplaceIcon.zip](https://github.com/pkowal1982/godoticonplugin/files/11341980/ReplaceIcon.zip)

**Comment by SussyGuy35** [comment]
@pkowal1982 
![ảnh](https://user-images.githubusercontent.com/107260269/234850839-3d3b9a30-0200-48b9-9d22-a0af31e1c013.png)

**Comment by pkowal1982** [comment]
Next try then. :)
[ReplaceIcon.zip](https://github.com/pkowal1982/godoticonplugin/files/11343464/ReplaceIcon.zip)

**Comment by SussyGuy35** [comment]
[output.txt](https://github.com/pkowal1982/godoticonplugin/files/11344026/output.txt)

**Comment by pkowal1982** [comment]
Ok, looks like icon loading works fine. But you probably use modified template for exporting your executable.
New version which prints out resources section:
[ReplaceIcon.zip](https://github.com/pkowal1982/godoticonplugin/files/11344274/ReplaceIcon.zip)

**Comment by SussyGuy35** [comment]
oh i see, that because im using modified template
tried with official template and it worked
sorry for bothering you :(

**Comment by pkowal1982** [comment]
There's one thing you can do. Just be sure that your modified template has icon created by IconCreator. Then it can be still used with IconReplacer.
