### ISSUE TITLE
Nonexistent function 'add_child' in base 'EditorInterface'.

### ISSUE THREAD

**Issue by iamalper** [pkowal1982/godoticonplugin#5]
I use Godot 4.2 and i use plugin from master brach.
When i click project>tools>Icon Creator, i get following error:
res://addons/godot_icon/GodotIconPlugin.gd:29 - Invalid call. Nonexistent function 'add_child' in base 'EditorInterface'.

**Comment by pkowal1982** [comment]
As it's stated in documentation plugin works for 3.5+ version and Godot 4 beta 2 up to Godot 4 beta 6.
Please add a comment in this thread: https://github.com/godotengine/godot/pull/75950
This PR adds icon/description manipulation so no plugin is needed.
Thanks for checking it out. :)
