### ISSUE TITLE
Getting Compilation Errors when installed

### ISSUE THREAD

**Issue by MacStevins** [pkowal1982/godoticonplugin#6]
Im using Godot 4.2.1 under Linux (Pop!_OS) using the Steam installation, and when installing the plugin it shows up on the output window as this
![image](https://github.com/pkowal1982/godoticonplugin/assets/15080111/78ee62ae-2cb1-4c2c-8fd2-907c6cb62653)

**Comment by pkowal1982** [comment]
As it's stated in documentation plugin works for 3.5+ version and Godot 4 beta 2 up to Godot 4 beta 6.
Please add a comment in this thread: https://github.com/godotengine/godot/pull/75950
This PR adds icon/description manipulation to Godot source so no plugin is needed.
Thanks for checking it out. :)
